MQTT_HOST = "your-mqtt-host"
MQTT_PORT = 8883  # or 1883
MQTT_USERNAME = "your-username"
MQTT_PASSWORD = "your-password"
DEVICE_SERIAL = "your-device-serial"
CAMERA_READ_TOPIC = f"bambu_a1_mini/request/{DEVICE_SERIAL}"
CAMERA_WRITE_TOPIC = f"bambu_a1_mini/response/{DEVICE_SERIAL}"
BUCKET_NAME = "your-bucket-name"
AWS_REGION = "your-region"
